apiVersion: v1
kind: Service
metadata:
  name: userservice
  namespace: default
spec:
  selector:
    app: userservice
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
  type: NodePort
